# Basic configuration for Kurtosis-Orbit
# Minimal setup for quick development and testing
orbit_config:
  # Essential chain identifiers
  chain_name: "MyBasicOrbit"
  chain_id: 412347
  
  # Use simple mode - single node acts as sequencer, validator, and batch poster
  simple_mode: true
  
  # Minimal services to save resources
  validator_count: 0  # Simple mode handles validation
  enable_bridge: true
  enable_explorer: false  # Disable to save resources