name: Simple Kurtosis-Orbit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test Orbit Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 25
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc
          docker system prune -a -f
          
      - name: Install Kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
          kurtosis version
      
      - name: Start Kurtosis Engine
        run: |
          kurtosis engine start
          sleep 10
          kurtosis engine status
      
      - name: Deploy Kurtosis-Orbit with Blockscout
        run: |
          echo "🚀 Deploying Arbitrum Orbit with Blockscout explorer..."
          kurtosis run . --enclave test-orbit \
            '{"orbit_config": {
              "chain_name": "CI-Test", 
              "chain_id": 999888, 
              "simple_mode": true,
              "enable_explorer": true,
              "enable_bridge": true
            }}'
        timeout-minutes: 20
      
      - name: Show Deployment Results
        run: |
          echo "✅ Deployment completed successfully!"
          echo "📊 Inspecting final enclave state..."
          kurtosis enclave inspect test-orbit
      
      - name: Export Debug Logs on Failure
        if: failure()
        run: |
          mkdir -p ./debug
          kurtosis enclave ls > ./debug/enclaves.txt || true
          kurtosis enclave dump test-orbit ./debug/ || true
          docker ps -a > ./debug/docker-containers.txt || true
          
      - name: Upload Debug Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: ./debug/
          retention-days: 3
      
      - name: Clean Up
        if: always()
        run: |
          kurtosis clean -a
          docker system prune -f